### ISSUE TITLE
Team email addresses

### ISSUE THREAD

**Issue by KarenLilje** [fireandlion/fireandlion#18]
@arthurattwell 
Please force "mail" and email address to always be together and not broken over 2 lines. See screen grab of example.
![screen shot 2017-08-29 at 1 25 05 pm](https://user-images.githubusercontent.com/16383283/29818638-96e50f46-8cbd-11e7-8346-543ee38bd92f.png)

**Comment by arthurattwell** [comment]
Tried a bit for a fancy solution, but decided a manual `&nbsp;` was indeed more efficient here! Fixed in 7959a437599554069c5bc21bafb66eb5c89efc60.
