### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by ChristinaRookie** [fireandlion/fireandlion#20]
I haven't got the repo on my new computer and am busy on other things, this is a reminder for me to do this ASAP:

In our thinking piece on CORE ['Producing the Economy with the EBW case study'](http://fireandlion.com/thinking/2017/08/29/producing-the-economy-with-the-ebw-case-study/) under 'Maths' section fix typo in 'notorously' to yield 'notoriously'.

**Comment by arthurattwell** [comment]
Thanks @ChristinaRookie! Fixed.
